version: '3.7'

services:

  front:
    image: sermalenk/skypro-front:lesson-37
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started

  api:
    image: rusikk83/skypro_course7:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#    ports:
#      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .env:/code/.env

  migrations:
    image: rusikk83/skypro_course7:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .env:/code/.env
    command: python todolist/manage.py migrate

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
#    ports:
#      - 5432:5432

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5



